# -----------------------------------------------------------------------------
# - sourced once before ~/.zshrc
# -----------------------------------------------------------------------------

# disable flow control
stty -ixon

# start the ssh-agent
[[ -z $TMUX ]] && eval "$(ssh-agent)"
