#!/bin/sh

# Executed by startx
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/* ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xset +fp $HOME/.fonts/ &
xset +fp /usr/share/fonts/local &
xset fp rehash &

# Set cursor
xsetroot -cursor_name Vanilla-DMZ &

xbindkeys &

# X killer
setxkbmap -option terminate:ctrl_alt_bksp &

# Speed up the keyboard
xset r rate 230 40

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Run systemd as a user instance
systemd --user &

exec openbox-session
