# -----------------------------------------------------------------------------
# - sourced once before ~/.zshrc
# -----------------------------------------------------------------------------

# disable flow control
stty -ixon

# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
