# -----------------------------------------------------------------------------
# - sourced in interactive shells after ~/.zshenv
# - used to set up aliases, functions, options, key bindings, etc.
# -----------------------------------------------------------------------------

# TODO: change to ~/.config/zsh
ZSH_DIR=$HOME/.zsh

function _source_configs() {
    for file in "$ZSH_DIR"/*.zsh
    do
        [[ -f "$file" ]] && source "$file"
    done
}

_source_configs
