# -----------------------------------------------------------------------------
# ~/.bashrc
# -----------------------------------------------------------------------------

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# -----------------------------------------------------------------------------
# OPTIONS
# -----------------------------------------------------------------------------
# History
HISTCONTROL=ignoredups:ignorespace:erasedups
HISTIGNORE=ls:l:ll:l1:la:df:du:top:bg:fg:cp:rm:mv:mkdir:reboot:suspend
HISTSIZE=5000
HISTFILESIZE=5000

shopt -s autocd
shopt -s cdspell
shopt -s cmdhist
shopt -s checkwinsize
shopt -s histappend
shopt -s histreedit
shopt -s expand_aliases
shopt -s extglob


# -----------------------------------------------------------------------------
# VARIABLES
# -----------------------------------------------------------------------------
# Terminal
[ -n "$TMUX" ] && export TERM=screen-256color || export TERM=xterm-256color

# Prompt
export PS1="\[\e[1;90m\]→ \W\[\e[0;31m\] $ \[\e[0m\]"


# -----------------------------------------------------------------------------
# COMPLETIONS
# -----------------------------------------------------------------------------
[[ -f $HOME/.rbenv/completions/rbenv.bash ]] && source $HOME/.rbenv/completions/rbenv.bash


# -----------------------------------------------------------------------------
# ALIASES
# -----------------------------------------------------------------------------
alias ls="ls --color=auto"
alias l="ls"
alias la="ls -A"
alias ll="ls -lh"
alias l1="ls -1"
alias lr="ls -R"
alias lx="ll -BX" # extension
alias lz="ll -rS" # size
alias lt="ll -rt" # date

alias ".."="cd ../"
alias "..."="cd ../../"
alias "...."="cd ../../../"

alias dir="dir --color=auto"
alias grep="grep --color=auto"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -Iv"
alias mkdir="mkdir -pv"
alias ln="ln -i"
alias df="df -h"
alias du="du -h"
alias free="free -h"
alias tree="tree -hF"
alias diff="colordiff"
alias h="history"
alias j="jobs -l"

alias now="date '+%B %d, %Y [%A] [%l:%M %p]'"
alias hgrep="history | grep $1"
alias ports="netstat -tulpn"
alias fping="ping -c 5 -n -i 0.2 -W1"
alias ftraceroute="traceroute -n -w 3 -q 1"
alias myip="wget -O - -q icanhazip.com"
alias xcopy="xclip -selection clipboard"
alias xpaste="xclip -selection clipboard -out"

# Arch Linux specific
if [[ -f /etc/arch-release ]]; then
    alias cltr="rm -rf ~/.local/share/Trash/"
    alias webcam="mpv -vf mirror -fps 15 tv:// -tv driver=v4l2:width=640:height=480:device=/dev/video0"
    alias reboot="systemctl reboot"
    alias poweroff="systemctl poweroff"
    alias halt="systemctl halt"
    alias suspnd="systemctl suspend"
    alias yolo="apacman -Syu"
fi


# -----------------------------------------------------------------------------
# FUNCTIONS
# -----------------------------------------------------------------------------
mkcd() {
    mkdir -p "$1"
    cd "$1"
}

tm() {
    local session="${1:-dev}"
    tmux new-session -A -s $session
}
