# Editor
export EDITOR="vim"
export VISUAL=$EDITOR


# Rython
[[ -f $HOME/.pyrc ]] && export PYTHONSTARTUP=$HOME/.pyrc


# Node.js
export NODE_REPL_HISTORY_SIZE=5000

if [[ -d $HOME/.npm-packages/bin ]]; then
  PATH="$HOME/.npm-packages/bin:$PATH"
  NODE_PATH="$HOME/.npm-packages/lib/node_modules"
fi


# Go
export GOPATH="$HOME/dev/.go"
export PATH="$PATH:$GOPATH/bin"


# Scripts
[[ -d $HOME/.bin ]] && PATH="$PATH:$HOME/.bin"


# Source ~/.bashrc
[[ -f $HOME/.bashrc ]] && source $HOME/.bashrc


# Android
export ANDROID_HOME=$HOME/android/sdk
export PATH=$ANDROID_HOME/tools:$PATH
export PATH=$ANDROID_HOME/tools/bin:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH


# Flutter
export PATH=$HOME/dev/.flutter/bin:$PATH
export CHROME_EXECUTABLE=chromium
